rm -rf CMakeFiles
rm -rf HU_Galaxy/cmake_install.cmake
rm -rf HU_Galaxy/CMakeCache.txt
rm -rf HU_Galaxy/_deps
rm -rf HU_Galaxy/HU_Galaxy_GalaxyWrapper.cpython-*
rm -rf HU_Galaxy/Makefile
rm -rf HU_Galaxy/CMakeFiles
rm -rf HU_Galaxy.egg-info
rm -rf build
rm -rf dist
rm -rf cmake-build-release
rm -rf manylinux_venv_c*
rm -rf auditedwheels/*
rm -f HU_Galaxy.cpython*
rm -f cmake-build-debug/CMakeCache.txt
rm -rf wheelhouse/*