version: '3'

services:
  pytorch-container:
    runtime: nvidia
    build:
      context: /home/mp74207/CLionProjects/HU_GalaxyPackage  # Replace with the path to the directory containing your Dockerfile
      dockerfile: Dockerfile  # Replace with the actual name of your Dockerfile if it's different
    volumes:
      - /home/mp74207/CLionProjects/HU_GalaxyPackage:/app
    working_dir: /app
    command:
      - /bin/bash
      - -c
      - |
        cd /app
        source /myvenv/bin/activate
        jupyter notebook --allow-root --ip 0.0.0.0 --port 8888  --no-browser     

    container_name: hu-galaxy-container
    ports:
      - "8888:8888"

#    command:
#      - /bin/bash
#      - -c
#      - "tail -f /dev/null"
#      - source /myvenv/bin/activate && jupyter-server