version: '3'
#  docker network create hu_galaxypackage_default
# Don't forget to make sure there is a default network

services:
  hu_galaxy_container:
    runtime: nvidia
    build:
      context: /home/mp74207/CLionProjects/HU_GalaxyPackage  # Replace with the path to the directory containing your Dockerfile
      dockerfile: Dockerfile  # Replace with the actual name of your Dockerfile if it's different
#    image: ny2292000/hu_galaxy_package:latest  # Use your image from Docker Hub
    volumes:
      - /home/mp74207/CLionProjects/HU_GalaxyPackage:/app
    working_dir: /app
    command:
      - /bin/bash
      - -c
#      - "tail -f /dev/null"
      - "cd /app && source /myvenv/bin/activate && jupyter notebook --allow-root --ip 0.0.0.0 --port 8888  --no-browser"
    container_name: hu-galaxy-container
    ports:
      - "8888:8888"
